// <auto-generated />
using System;
using GdeWebDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GdeWebDB.Migrations
{
    [DbContext(typeof(GdeDbContext))]
    [Migration("20251107075837_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GdeWebDB.Entities.AuthToken", b =>
                {
                    b.Property<int>("TOKENID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EXPIRATIONDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("TOKEN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("USERID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TOKENID");

                    b.HasIndex("USERID");

                    b.ToTable("T_AUTHENTICATION", (string)null);
                });

            modelBuilder.Entity("GdeWebDB.Entities.Course", b =>
                {
                    b.Property<int>("COURSEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("COURSEAIREQUESTJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("COURSEAIRESPONSEJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("COURSEDB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("COURSEDESCRIPTION")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("COURSEFILE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("COURSEFILETEXT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("COURSEMEDIA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("COURSEMEDIADURATION")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("COURSEMEDIATEXT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("COURSESUMMARYKEYWORDS")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("COURSETITLE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MODIFICATIONDATE")
                        .HasColumnType("TEXT");

                    b.HasKey("COURSEID");

                    b.ToTable("A_COURSE", (string)null);
                });

            modelBuilder.Entity("GdeWebDB.Entities.Quiz", b =>
                {
                    b.Property<int>("QUIZID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("COURSEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("MODIFICATIONDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("QUIZANSWER1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QUIZANSWER2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QUIZANSWER3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QUIZANSWER4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QUIZQUESTION")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QUIZSUCCESS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QUIZID");

                    b.ToTable("A_QUIZ", (string)null);
                });

            modelBuilder.Entity("GdeWebDB.Entities.Role", b =>
                {
                    b.Property<int>("ROLEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MODIFICATIONDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("MODIFIER")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ROLENAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("VALID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("ROLEID");

                    b.ToTable("T_ROLE", (string)null);

                    b.HasData(
                        new
                        {
                            ROLEID = 1,
                            MODIFICATIONDATE = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MODIFIER = 1,
                            ROLENAME = "Admin",
                            VALID = true
                        },
                        new
                        {
                            ROLEID = 2,
                            MODIFICATIONDATE = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MODIFIER = 1,
                            ROLENAME = "User",
                            VALID = true
                        });
                });

            modelBuilder.Entity("GdeWebDB.Entities.User", b =>
                {
                    b.Property<int>("USERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ACTIVE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("EMAIL")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FIRSTNAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LASTNAME")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MODIFICATIONDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("USERDATAJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("USERID");

                    b.ToTable("T_USER", (string)null);

                    b.HasData(
                        new
                        {
                            USERID = 1,
                            ACTIVE = true,
                            EMAIL = "jakab.d@gmail.com",
                            FIRSTNAME = "Dávid",
                            GUID = "0d2f1a91-ba24-4203-9b89-2d7f19ac9a7a",
                            LASTNAME = "Jakab",
                            MODIFICATIONDATE = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PASSWORD = "3774b62586f7e44b343a0f2cc8e0e336c0d03549e09162cb73dfcb9a72c15a95c40f5a5b1608a08a28a79f46450ad3391f0a9342a19fdebb56511b556ba6aabb",
                            USERDATAJSON = "{}"
                        });
                });

            modelBuilder.Entity("GdeWebDB.Entities.UserRole", b =>
                {
                    b.Property<int>("USERROLES")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CREATINGDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("CREATOR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ROLEID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("USERID")
                        .HasColumnType("INTEGER");

                    b.HasKey("USERROLES");

                    b.HasIndex("ROLEID");

                    b.HasIndex("USERID");

                    b.ToTable("K_USER_ROLES", (string)null);

                    b.HasData(
                        new
                        {
                            USERROLES = 1,
                            CREATINGDATE = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CREATOR = 1,
                            ROLEID = 1,
                            USERID = 1
                        });
                });

            modelBuilder.Entity("GdeWebDB.Entities.AuthToken", b =>
                {
                    b.HasOne("GdeWebDB.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("USERID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GdeWebDB.Entities.UserRole", b =>
                {
                    b.HasOne("GdeWebDB.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("ROLEID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GdeWebDB.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("USERID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GdeWebDB.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GdeWebDB.Entities.User", b =>
                {
                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
